### ISSUE TITLE
Request for SI units

### ISSUE THREAD

**Issue by shimwell** [aidancrilly/NeSST#21]
Just wondering if anyone would mind if the package was changed to use SI units 

for example the dNdE_TT method expects MeV and ion_temperature is in KeV

Would it be acceptable to switch to eV as inputs and output units everywhere?

If so I'm happy to make a PR.

**Comment by aidancrilly** [comment]
Sure, I see no issue with this. The only argument for MeV is that it is data format of both the CODATA mass values and ENDF cross sections but such an easy conversion to SI.

Thank you for offering to make the PR

**Comment by aidancrilly** [comment]
Closed by #27
