### ISSUE TITLE
Request to change DD/DT primspecmoments from variance to standard deviation 

### ISSUE THREAD

**Issue by shimwell** [aidancrilly/NeSST#29]
Wondering if standard deviation might be a nicer value to return instead of variance.

The units could be eV which would be the same as mean instead of eV**2. This makes it easy to see the +/- with regards to energy.

Also it just so happens that [openmc accepts standard deviation](https://docs.openmc.org/en/stable/pythonapi/generated/openmc.stats.Normal.html#openmc.stats.Normal) when defining source terms with normal distributions.

This will have some knock on consequences for methods that accept variance. But should be easy to accept standard deviation instead and do some internal conversion if needed.

**Comment by aidancrilly** [comment]
Variance is useful in other contexts i.e. the effect of fluid velocity variance, so I think best if primspecmoments returns both variance and standard deviation

**Comment by shimwell** [comment]
solved by PR #30 🎉
