### ISSUE TITLE
feature request: yields unrelated to DT yield

### ISSUE THREAD

**Issue by shimwell** [aidancrilly/NeSST#40]
Just wondering if it would be worth trying to get the code to give yields that are not relative to the DT yield.

Currently yields are related to the DT yield but perhaps they could be absolute yields

perhaps a new function called yields_normalised could be made where the neutron yield of DD, DD, DT and TT reactions are found and 4 numbers are returned which all sum to 1?

**Comment by aidancrilly** [comment]
Hi Jon,

Thanks for your patience with the new issues, I am just back from parental leave and getting into the swing of things. Added a function for this to https://github.com/aidancrilly/NeSST/tree/yields_normalised works like so:
```python3
# Sum of primary yields is unity
Y_DT,Y_DD,Y_TT = nst.yields_normalised(Tion,frac_D=frac_D,frac_T=frac_T)
```

Will merge into master shortly
